AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Parallax Lambdas

Globals:
  Function:
    Runtime: python3.14
    Timeout: 120
    MemorySize: 512
    Architectures:
      - x86_64
    Environment:
      Variables:
        LOG_LEVEL: INFO

Resources:
  ParallaxFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: parallax-main
      Handler: signal_generation_engine.lambda_handler
      CodeUri: src/
      Policies:
        - AWSLambdaBasicExecutionRole
      # If you need VPC:
      # VpcConfig:
      #   SecurityGroupIds: [...]
      #   SubnetIds: [...]

Outputs:
  FunctionName:
    Value: !Ref ParallaxFunction