variable "environment" {}
variable "aws_region" {}
variable "instance_type" {}
variable "subnet_id" {}
variable "vpc_id" {}
variable "instance_profile" {}
variable "ecr_repository_url" {}
variable "image_tag" {}
variable "key_name" {}
