INDEX_SYMBOLS = {
        "nifty50":   {"exchange": "NSE_INDEX|Nifty 50",        "security_id": "13"},
        "banknifty": {"exchange": "NSE_INDEX|Nifty Bank",       "security_id": "25"},
        "finnifty":  {"exchange": "NSE_INDEX|Nifty Fin Service","security_id": "27"},
        "sensex":    {"exchange": "BSE_INDEX|SENSEX",           "security_id": "51"},
    }
EQUITY_SYMBOLS = {
        "ONGC":       {"exchange": "NSE_EQ", "isin": "INE213A01029", "security_id": "2475"},
        "WIPRO":      {"exchange": "NSE_EQ", "isin": "INE075A01022", "security_id": "3787"},
        "BHARTIARTL": {"exchange": "NSE_EQ", "isin": "INE397D01024", "security_id": "10604"},
        "TCS":        {"exchange": "NSE_EQ", "isin": "INE467B01029", "security_id": "11536"},
        "COALINDIA":  {"exchange": "NSE_EQ", "isin": "INE522F01014", "security_id": "20374"},
        "POWERGRID":  {"exchange": "NSE_EQ", "isin": "INE752E01010", "security_id": "14977"},
        "SUNPHARMA":  {"exchange": "NSE_EQ", "isin": "INE044A01036", "security_id": "3351"},
        "CIPLA":      {"exchange": "NSE_EQ", "isin": "INE059A01026", "security_id": "694"},
        "GRASIM":     {"exchange": "NSE_EQ", "isin": "INE047A01021", "security_id": "1232"},
        "HDFCLIFE":   {"exchange": "NSE_EQ", "isin": "INE795G01014", "security_id": "467"},
        "ITC":        {"exchange": "NSE_EQ", "isin": "INE154A01025", "security_id": "1660"},
        "HINDALCO":   {"exchange": "NSE_EQ", "isin": "INE038A01020", "security_id": "1363"},
        "APOLLOHOSP": {"exchange": "NSE_EQ", "isin": "INE437A01024", "security_id": "157"},
        "NTPC":       {"exchange": "NSE_EQ", "isin": "INE733E01010", "security_id": "11630"},
        "NESTLEIND":  {"exchange": "NSE_EQ", "isin": "INE239A01024", "security_id": "17963"},
        "INFY":       {"exchange": "NSE_EQ", "isin": "INE009A01021", "security_id": "1594"},
        "ULTRACEMCO": {"exchange": "NSE_EQ", "isin": "INE481G01011", "security_id": "11532"},
        "KOTAKBANK":  {"exchange": "NSE_EQ", "isin": "INE237A01036", "security_id": "1922"},
        "MAXHEALTH":  {"exchange": "NSE_EQ", "isin": "INE027H01010",  "security_id": "22377"},
        "TATACONSUM": {"exchange": "NSE_EQ", "isin": "INE192A01025", "security_id": "3432"},
        "SBILIFE":    {"exchange": "NSE_EQ", "isin": "INE123W01016", "security_id": "21808"},
        "TITAN":      {"exchange": "NSE_EQ", "isin": "INE280A01028", "security_id": "3506"},
        "AXISBANK":   {"exchange": "NSE_EQ", "isin": "INE238A01034", "security_id": "5900"},
        "DRREDDY":    {"exchange": "NSE_EQ", "isin": "INE089A01031", "security_id": "881"},
        "HCLTECH":    {"exchange": "NSE_EQ", "isin": "INE860A01027", "security_id": "7229"},
        "TECHM":      {"exchange": "NSE_EQ", "isin": "INE669C01036", "security_id": "13538"},
        "BAJAJ-AUTO": {"exchange": "NSE_EQ", "isin": "INE917I01010", "security_id": "16669"},
        "ICICIBANK":  {"exchange": "NSE_EQ", "isin": "INE090A01021", "security_id": "4963"},
        "TATASTEEL":  {"exchange": "NSE_EQ", "isin": "INE081A01020", "security_id": "3499"},
        "BEL":        {"exchange": "NSE_EQ", "isin": "INE263A01024", "security_id": "383"},
        "TRENT":      {"exchange": "NSE_EQ", "isin": "INE849A01020", "security_id": "1964"},
        "LT":         {"exchange": "NSE_EQ", "isin": "INE018A01030", "security_id": "11483"},
        "JSWSTEEL":   {"exchange": "NSE_EQ", "isin": "INE019A01038", "security_id": "11723"},
        "JIOFIN":     {"exchange": "NSE_EQ", "isin": "INE758E01017", "security_id": "18143"},
        "MARUTI":     {"exchange": "NSE_EQ", "isin": "INE585B01010", "security_id": "10999"},
        "ADANIPORTS": {"exchange": "NSE_EQ", "isin": "INE742F01042", "security_id": "15083"},
        "M&M":        {"exchange": "NSE_EQ", "isin": "INE101A01026", "security_id": "2031"},
        "ASIANPAINT": {"exchange": "NSE_EQ", "isin": "INE021A01026", "security_id": "236"},
        "EICHERMOT":  {"exchange": "NSE_EQ", "isin": "INE066A01021", "security_id": "910"},
        "HINDUNILVR": {"exchange": "NSE_EQ", "isin": "INE030A01027", "security_id": "1394"},
        "BAJAJFINSV": {"exchange": "NSE_EQ", "isin": "INE918I01026", "security_id": "16675"},
        "HDFCBANK":   {"exchange": "NSE_EQ", "isin": "INE040A01034", "security_id": "1333"},
        "ADANIENT":   {"exchange": "NSE_EQ", "isin": "INE423A01024", "security_id": "25"},
        "SBIN":       {"exchange": "NSE_EQ", "isin": "INE062A01020", "security_id": "3045"},
        "ETERNAL":    {"exchange": "NSE_EQ", "isin": "INE758T01015", "security_id": "5097"},
        "BAJFINANCE": {"exchange": "NSE_EQ", "isin": "INE296A01032", "security_id": "317"},
        "INDIGO":     {"exchange": "NSE_EQ", "isin": "INE646L01027", "security_id": "11195"},
        "RELIANCE":   {"exchange": "NSE_EQ", "isin": "INE002A01018", "security_id": "2885"},
        "TMPV":       {"exchange": "NSE_EQ", "isin": "INE155A01022", "security_id": "3456"},
        "SHRIRAMFIN": {"exchange": "NSE_EQ", "isin": "INE721A01047", "security_id": "4306"},
    }
US_INDEX_SYMBOLS = {
    "SP500":    {"ticker": "^GSPC"},
    "NASDAQ":   {"ticker": "^IXIC"},
    "DOWJONES": {"ticker": "^DJI"},
}

US_EQUITY_SYMBOLS = {
    # Dow Jones 30
    "AAPL":   {"ticker": "AAPL"},
    "AMGN":   {"ticker": "AMGN"},
    "AXP":    {"ticker": "AXP"},
    "BA":     {"ticker": "BA"},
    "CAT":    {"ticker": "CAT"},
    "CRM":    {"ticker": "CRM"},
    "CSCO":   {"ticker": "CSCO"},
    "CVX":    {"ticker": "CVX"},
    "DIS":    {"ticker": "DIS"},
    "GS":     {"ticker": "GS"},
    "HD":     {"ticker": "HD"},
    "HON":    {"ticker": "HON"},
    "IBM":    {"ticker": "IBM"},
    "JNJ":    {"ticker": "JNJ"},
    "JPM":    {"ticker": "JPM"},
    "KO":     {"ticker": "KO"},
    "MCD":    {"ticker": "MCD"},
    "MMM":    {"ticker": "MMM"},
    "MRK":    {"ticker": "MRK"},
    "MSFT":   {"ticker": "MSFT"},
    "NKE":    {"ticker": "NKE"},
    "NVDA":   {"ticker": "NVDA"},
    "PG":     {"ticker": "PG"},
    "SHW":    {"ticker": "SHW"},
    "TRV":    {"ticker": "TRV"},
    "UNH":    {"ticker": "UNH"},
    "V":      {"ticker": "V"},
    "VZ":     {"ticker": "VZ"},
    "WMT":    {"ticker": "WMT"},
    "AMZN":   {"ticker": "AMZN"},
    # NASDAQ-100 (not in Dow)
    "META":   {"ticker": "META"},
    "GOOGL":  {"ticker": "GOOGL"},
    "TSLA":   {"ticker": "TSLA"},
    "AVGO":   {"ticker": "AVGO"},
    "COST":   {"ticker": "COST"},
    "NFLX":   {"ticker": "NFLX"},
    "AMD":    {"ticker": "AMD"},
    "QCOM":   {"ticker": "QCOM"},
    "INTU":   {"ticker": "INTU"},
    "AMAT":   {"ticker": "AMAT"},
    "MU":     {"ticker": "MU"},
    "LRCX":   {"ticker": "LRCX"},
    "KLAC":   {"ticker": "KLAC"},
    "MRVL":   {"ticker": "MRVL"},
    "PANW":   {"ticker": "PANW"},
    "ADSK":   {"ticker": "ADSK"},
    "CRWD":   {"ticker": "CRWD"},
    "MELI":   {"ticker": "MELI"},
    "FTNT":   {"ticker": "FTNT"},
    "SNPS":   {"ticker": "SNPS"},
    "CDNS":   {"ticker": "CDNS"},
    "PLTR":   {"ticker": "PLTR"},
    "INTC":   {"ticker": "INTC"},
    "SBUX":   {"ticker": "SBUX"},
    "GILD":   {"ticker": "GILD"},
    "REGN":   {"ticker": "REGN"},
    "VRTX":   {"ticker": "VRTX"},
    "ISRG":   {"ticker": "ISRG"},
    "BKNG":   {"ticker": "BKNG"},
    "PYPL":   {"ticker": "PYPL"},
    # S&P 500 large caps (not already listed)
    "LLY":    {"ticker": "LLY"},
    "ABBV":   {"ticker": "ABBV"},
    "XOM":    {"ticker": "XOM"},
    "BAC":    {"ticker": "BAC"},
    "MA":     {"ticker": "MA"},
    "TMO":    {"ticker": "TMO"},
    "ABT":    {"ticker": "ABT"},
    "ACN":    {"ticker": "ACN"},
    "NEE":    {"ticker": "NEE"},
    "PEP":    {"ticker": "PEP"},
    "ORCL":   {"ticker": "ORCL"},
    "PM":     {"ticker": "PM"},
    "MS":     {"ticker": "MS"},
    "BLK":    {"ticker": "BLK"},
    "SPGI":   {"ticker": "SPGI"},
    "T":      {"ticker": "T"},
    "LOW":    {"ticker": "LOW"},
    "DE":     {"ticker": "DE"},
    "UPS":    {"ticker": "UPS"},
    "RTX":    {"ticker": "RTX"},
    "LMT":    {"ticker": "LMT"},
    "GE":     {"ticker": "GE"},
    "F":      {"ticker": "F"},
    "GM":     {"ticker": "GM"},
    "BRK-B":  {"ticker": "BRK-B"},
    "UBER":   {"ticker": "UBER"},
    "ABNB":   {"ticker": "ABNB"},
    "ARM":    {"ticker": "ARM"},
}

SYMBOL_REGISTRY = {
    "INDEX":     INDEX_SYMBOLS,
    "EQUITY":    EQUITY_SYMBOLS,
    "US_INDEX":  US_INDEX_SYMBOLS,
    "US_EQUITY": US_EQUITY_SYMBOLS,
}
def resolve_symbol_map(mode: str) -> dict:
    """
    Returns the correct symbol map based on the trading mode.
    Raises ValueError for unsupported modes.
    """
    symbol_map = SYMBOL_REGISTRY.get(mode.upper())
    if symbol_map is None:
        raise ValueError(f"Unsupported mode '{mode}'. Expected one of: {list(SYMBOL_REGISTRY.keys())}")
    return symbol_map